//! Raw FFI bindings to MLT (Media Lovin' Toolkit).
//! Generated by bindgen at build time from system MLT headers.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
